config/routes.rb
Rails.application.routes.draw do
  root to:'public/homes#top'

  #ユーザー用
  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  #ユーザー側
  scope module: :public do
    get 'homes/top'
    get 'homes/about'
    get 'users/:id/favorites' => 'users#favorites', as:'user_favorites'
    patch 'users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
    resources :favo_images do
      collection do
        get:search
      end
      resource :favorites, only:[:create, :destroy]
      resources :favo_comments, only:[:create, :destroy]
    end
    resources :users do
      member do
        get :follows, :followers
      end
      collection do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favo_comment.rb
class FavoComment < ApplicationRecord
  belongs_to :user
  belongs_to :favo_image
  
  has_many :notifications, dependent: :destroy
end

app/models/favo_image.rb
class FavoImage < ApplicationRecord
  has_one_attached :image
  validates :image, presence: true
  validates :location, presence:true
  validates :caption, presence:true
  belongs_to :user
  has_many :favo_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :notifications, dependent: :destroy
  
  #いいね 
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and favo_image_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        favo_image_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end
  
  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end
  # コメント
  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
  
  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  image.variant(resize_to_limit: [width, height]).processed
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  # DB検索用の設定
  def self.search(keyword)
    where(["location like? OR caption like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favo_image
end

app/models/notification.rb
class Notification < ApplicationRecord
  # public配下？
  default_scope->{order(created_at: :desc)}

  belongs_to :favo_iamge, optional: true
  belongs_to :favo_comment, optional: true
  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
  
  default_scope -> { order(created_at: :desc) }
  belongs_to :favo_image, optional: true
  belongs_to :favo_comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :favo_iamge
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :introduction, presence: true

  has_many :favo_images, dependent: :destroy
  has_many :favo_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # フォローされる側
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローする側
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  has_one_attached :profile_image

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_profile_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    homes_about_path
  end

  def after_sign_out_path_for(resource)
    homes_top_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:introduction,:profile_image])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Favoplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand p-3" href="/"><i class="far fa-hand-spock fa-2x"></i>Favo Place</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class = "nav-item">
                  <!--キーワード検索窓-->
                    <div class="search-form">
                      <%= form_with url: search_favo_images_path, method: :get, local: true do |f| %>
                        <%= f.text_field :keyword, value: @keyword, placeholder:"キーワード検索" %>
                        <%= f.submit "検索", class:"btn btn-outline-success" %>
                      <% end %>
                    </div>
                </li>
                <li class = "nav-item">
                  <%= link_to "Post", new_favo_image_path, class:'nav-link text-dark' %>
                </li>
                <li class = "nav-item">
                  <%= link_to "Find", favo_images_path, class:'nav-link text-dark' %>
                </li>
                <li>
                  <%= link_to "Users", users_path, class:'nav-link text-dark' %>
                </li>
                <li class = "nav-item">
                  <%= link_to "#{current_user.name}'s page", user_path(current_user.id), class:'nav-link text-dark' %>
                </li>
                <li class = "nav-item">
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class:'nav-link text-dark' %>
                </li>
              <% else %>
                <li class = "nav-item">
                  <%= link_to "Log in", new_user_session_path, class:'nav-link text-dark' %>
                </li>
                <li class = "nav-item">
                  <%= link_to "Sign up", new_user_registration_path, class:'nav-link text-dark' %>
                </li>
              <% end %>
              </ul>
            </div>
        </div>
    </div>
    </header>
    <main class = "mb-auto">
      <%= yield %>
    </main>

    <div class="container">
      <footer class="pb-3 my-4 nav-bg">
        <div class="footer-bg pt-3">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item"><%= link_to "Favo Place", root_path, class: 'nav-link px-2 text-black nav-item' %></li>
          <li class="nav-item"><%= link_to "About", homes_about_path, class: 'nav-link px-2 text-black' %></li>
          <li class="nav-item my-2">
            <%= link_to "#", class: 'text-decoration-none insta' do %>
            <i class="fab fa-instagram fa-2x"></i>
            <% end %>
            <%= link_to "#", class: 'text-decoration-none' do %>
            <i class="fab fa-twitter fa-2x"></i>
            <% end %>
            <%= link_to "#", class: 'text-decoration-none fb-square' do %>
            <i class="fab fa-facebook fa-2x"></i>
            <% end %>
          </li>
        </ul>
        </div>
        <div class="nav-bg">
          <p class="text-center text-black">© 2022 Favo Place</p>
        </div>
      </footer>
    </div>

  </body>
</html>

app/views/notifications/_notification.html.erb
<% visiter = notification.visiter %>
<% item = notification.favo_image %>

<div class="user-view clearfix ">
  <%= link_to users_user_path(notification.visiter) do %>
    <%= attachment_image_tag visiter, :profile_image, :fill,100,100, format: "jpeg", fallback: "no_image.jpg", size: "50x50", class:"profile-img-circle" %>
  <% end %>
  <%= notification_form(notification) %><span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)} 前)" %></span>
  <br>
  <% if !favo_comment.nil? %>
    <p class="moderate-font text-center" style="color: #C0C0C0;"><%= favo_comment %></p>
  <% end %>
</div>

app/views/notifications/index.html.erb
<h3 class="text-center">通知</h3>
    <%= link_to destroy_all_users_notifications_path, method: :delete do %>
        <i class="fas fa-trash" style="color: black;"></i>
        <h7 style="color: black;">全削除</h7>
    <% end %>
    <hr>
<% if @notifications.exists? %>
    <div class="users-index">
        <%= render @notifications %>
    </div>
<% else %>
    <p>通知はありません</p>
<% end %>